# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: device_state_requests.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import device_state_structures_pb2 as device__state__structures__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='device_state_requests.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1b\x64\x65vice_state_requests.proto\x1a\x1d\x64\x65vice_state_structures.proto\"\x16\n\x14GetAllDevicesRequest\"1\n\x15GetAllDevicesResponse\x12\x18\n\x07\x64\x65vices\x18\x01 \x03(\x0b\x32\x07.Device\"+\n\x14GetDeviceByIdRequest\x12\x13\n\x0b\x64\x65vice_uuid\x18\x01 \x01(\t\"0\n\x15GetDeviceByIdResponse\x12\x17\n\x06\x64\x65vice\x18\x01 \x01(\x0b\x32\x07.Device\"Y\n\x19GetDevicesByFilterRequest\x12\x13\n\x0b\x64\x65vice_uuid\x18\x01 \x03(\t\x12\x12\n\ndevice_pid\x18\x02 \x03(\t\x12\x13\n\x0b\x64\x65vice_name\x18\x03 \x03(\t\"6\n\x1aGetDevicesByFilterResponse\x12\x18\n\x07\x64\x65vices\x18\x01 \x03(\x0b\x32\x07.Device\"\xd4\x01\n\rDeviceRequest\x12\x38\n\x17get_all_devices_request\x18\x01 \x01(\x0b\x32\x15.GetAllDevicesRequestH\x00\x12\x39\n\x18get_device_by_id_request\x18\x02 \x01(\x0b\x32\x15.GetDeviceByIdRequestH\x00\x12\x43\n\x1dget_devices_by_filter_request\x18\x03 \x01(\x0b\x32\x1a.GetDevicesByFilterRequestH\x00\x42\t\n\x07request\"\xcc\x01\n\x0e\x44\x65viceResponse\x12:\n\x18get_all_devices_response\x18\x01 \x01(\x0b\x32\x16.GetAllDevicesResponseH\x00\x12;\n\x19get_device_by_id_response\x18\x02 \x01(\x0b\x32\x16.GetDeviceByIdResponseH\x00\x12\x35\n\x0eget_devices_by\x18\x03 \x01(\x0b\x32\x1b.GetDevicesByFilterResponseH\x00\x42\n\n\x08response\"D\n\x13\x44\x65viceResponseError\x12$\n\x0c\x64\x65vice_error\x18\x01 \x01(\x0b\x32\x0c.DeviceErrorH\x00\x42\x07\n\x05\x65rrorb\x06proto3')
  ,
  dependencies=[device__state__structures__pb2.DESCRIPTOR,])




_GETALLDEVICESREQUEST = _descriptor.Descriptor(
  name='GetAllDevicesRequest',
  full_name='GetAllDevicesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=84,
)


_GETALLDEVICESRESPONSE = _descriptor.Descriptor(
  name='GetAllDevicesResponse',
  full_name='GetAllDevicesResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='devices', full_name='GetAllDevicesResponse.devices', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=135,
)


_GETDEVICEBYIDREQUEST = _descriptor.Descriptor(
  name='GetDeviceByIdRequest',
  full_name='GetDeviceByIdRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='device_uuid', full_name='GetDeviceByIdRequest.device_uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=180,
)


_GETDEVICEBYIDRESPONSE = _descriptor.Descriptor(
  name='GetDeviceByIdResponse',
  full_name='GetDeviceByIdResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='device', full_name='GetDeviceByIdResponse.device', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=182,
  serialized_end=230,
)


_GETDEVICESBYFILTERREQUEST = _descriptor.Descriptor(
  name='GetDevicesByFilterRequest',
  full_name='GetDevicesByFilterRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='device_uuid', full_name='GetDevicesByFilterRequest.device_uuid', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='device_pid', full_name='GetDevicesByFilterRequest.device_pid', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='device_name', full_name='GetDevicesByFilterRequest.device_name', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=232,
  serialized_end=321,
)


_GETDEVICESBYFILTERRESPONSE = _descriptor.Descriptor(
  name='GetDevicesByFilterResponse',
  full_name='GetDevicesByFilterResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='devices', full_name='GetDevicesByFilterResponse.devices', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=323,
  serialized_end=377,
)


_DEVICEREQUEST = _descriptor.Descriptor(
  name='DeviceRequest',
  full_name='DeviceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='get_all_devices_request', full_name='DeviceRequest.get_all_devices_request', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='get_device_by_id_request', full_name='DeviceRequest.get_device_by_id_request', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='get_devices_by_filter_request', full_name='DeviceRequest.get_devices_by_filter_request', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='request', full_name='DeviceRequest.request',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=380,
  serialized_end=592,
)


_DEVICERESPONSE = _descriptor.Descriptor(
  name='DeviceResponse',
  full_name='DeviceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='get_all_devices_response', full_name='DeviceResponse.get_all_devices_response', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='get_device_by_id_response', full_name='DeviceResponse.get_device_by_id_response', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='get_devices_by', full_name='DeviceResponse.get_devices_by', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='response', full_name='DeviceResponse.response',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=595,
  serialized_end=799,
)


_DEVICERESPONSEERROR = _descriptor.Descriptor(
  name='DeviceResponseError',
  full_name='DeviceResponseError',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='device_error', full_name='DeviceResponseError.device_error', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='error', full_name='DeviceResponseError.error',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=801,
  serialized_end=869,
)

_GETALLDEVICESRESPONSE.fields_by_name['devices'].message_type = device__state__structures__pb2._DEVICE
_GETDEVICEBYIDRESPONSE.fields_by_name['device'].message_type = device__state__structures__pb2._DEVICE
_GETDEVICESBYFILTERRESPONSE.fields_by_name['devices'].message_type = device__state__structures__pb2._DEVICE
_DEVICEREQUEST.fields_by_name['get_all_devices_request'].message_type = _GETALLDEVICESREQUEST
_DEVICEREQUEST.fields_by_name['get_device_by_id_request'].message_type = _GETDEVICEBYIDREQUEST
_DEVICEREQUEST.fields_by_name['get_devices_by_filter_request'].message_type = _GETDEVICESBYFILTERREQUEST
_DEVICEREQUEST.oneofs_by_name['request'].fields.append(
  _DEVICEREQUEST.fields_by_name['get_all_devices_request'])
_DEVICEREQUEST.fields_by_name['get_all_devices_request'].containing_oneof = _DEVICEREQUEST.oneofs_by_name['request']
_DEVICEREQUEST.oneofs_by_name['request'].fields.append(
  _DEVICEREQUEST.fields_by_name['get_device_by_id_request'])
_DEVICEREQUEST.fields_by_name['get_device_by_id_request'].containing_oneof = _DEVICEREQUEST.oneofs_by_name['request']
_DEVICEREQUEST.oneofs_by_name['request'].fields.append(
  _DEVICEREQUEST.fields_by_name['get_devices_by_filter_request'])
_DEVICEREQUEST.fields_by_name['get_devices_by_filter_request'].containing_oneof = _DEVICEREQUEST.oneofs_by_name['request']
_DEVICERESPONSE.fields_by_name['get_all_devices_response'].message_type = _GETALLDEVICESRESPONSE
_DEVICERESPONSE.fields_by_name['get_device_by_id_response'].message_type = _GETDEVICEBYIDRESPONSE
_DEVICERESPONSE.fields_by_name['get_devices_by'].message_type = _GETDEVICESBYFILTERRESPONSE
_DEVICERESPONSE.oneofs_by_name['response'].fields.append(
  _DEVICERESPONSE.fields_by_name['get_all_devices_response'])
_DEVICERESPONSE.fields_by_name['get_all_devices_response'].containing_oneof = _DEVICERESPONSE.oneofs_by_name['response']
_DEVICERESPONSE.oneofs_by_name['response'].fields.append(
  _DEVICERESPONSE.fields_by_name['get_device_by_id_response'])
_DEVICERESPONSE.fields_by_name['get_device_by_id_response'].containing_oneof = _DEVICERESPONSE.oneofs_by_name['response']
_DEVICERESPONSE.oneofs_by_name['response'].fields.append(
  _DEVICERESPONSE.fields_by_name['get_devices_by'])
_DEVICERESPONSE.fields_by_name['get_devices_by'].containing_oneof = _DEVICERESPONSE.oneofs_by_name['response']
_DEVICERESPONSEERROR.fields_by_name['device_error'].message_type = device__state__structures__pb2._DEVICEERROR
_DEVICERESPONSEERROR.oneofs_by_name['error'].fields.append(
  _DEVICERESPONSEERROR.fields_by_name['device_error'])
_DEVICERESPONSEERROR.fields_by_name['device_error'].containing_oneof = _DEVICERESPONSEERROR.oneofs_by_name['error']
DESCRIPTOR.message_types_by_name['GetAllDevicesRequest'] = _GETALLDEVICESREQUEST
DESCRIPTOR.message_types_by_name['GetAllDevicesResponse'] = _GETALLDEVICESRESPONSE
DESCRIPTOR.message_types_by_name['GetDeviceByIdRequest'] = _GETDEVICEBYIDREQUEST
DESCRIPTOR.message_types_by_name['GetDeviceByIdResponse'] = _GETDEVICEBYIDRESPONSE
DESCRIPTOR.message_types_by_name['GetDevicesByFilterRequest'] = _GETDEVICESBYFILTERREQUEST
DESCRIPTOR.message_types_by_name['GetDevicesByFilterResponse'] = _GETDEVICESBYFILTERRESPONSE
DESCRIPTOR.message_types_by_name['DeviceRequest'] = _DEVICEREQUEST
DESCRIPTOR.message_types_by_name['DeviceResponse'] = _DEVICERESPONSE
DESCRIPTOR.message_types_by_name['DeviceResponseError'] = _DEVICERESPONSEERROR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetAllDevicesRequest = _reflection.GeneratedProtocolMessageType('GetAllDevicesRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETALLDEVICESREQUEST,
  __module__ = 'device_state_requests_pb2'
  # @@protoc_insertion_point(class_scope:GetAllDevicesRequest)
  ))
_sym_db.RegisterMessage(GetAllDevicesRequest)

GetAllDevicesResponse = _reflection.GeneratedProtocolMessageType('GetAllDevicesResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETALLDEVICESRESPONSE,
  __module__ = 'device_state_requests_pb2'
  # @@protoc_insertion_point(class_scope:GetAllDevicesResponse)
  ))
_sym_db.RegisterMessage(GetAllDevicesResponse)

GetDeviceByIdRequest = _reflection.GeneratedProtocolMessageType('GetDeviceByIdRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETDEVICEBYIDREQUEST,
  __module__ = 'device_state_requests_pb2'
  # @@protoc_insertion_point(class_scope:GetDeviceByIdRequest)
  ))
_sym_db.RegisterMessage(GetDeviceByIdRequest)

GetDeviceByIdResponse = _reflection.GeneratedProtocolMessageType('GetDeviceByIdResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETDEVICEBYIDRESPONSE,
  __module__ = 'device_state_requests_pb2'
  # @@protoc_insertion_point(class_scope:GetDeviceByIdResponse)
  ))
_sym_db.RegisterMessage(GetDeviceByIdResponse)

GetDevicesByFilterRequest = _reflection.GeneratedProtocolMessageType('GetDevicesByFilterRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETDEVICESBYFILTERREQUEST,
  __module__ = 'device_state_requests_pb2'
  # @@protoc_insertion_point(class_scope:GetDevicesByFilterRequest)
  ))
_sym_db.RegisterMessage(GetDevicesByFilterRequest)

GetDevicesByFilterResponse = _reflection.GeneratedProtocolMessageType('GetDevicesByFilterResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETDEVICESBYFILTERRESPONSE,
  __module__ = 'device_state_requests_pb2'
  # @@protoc_insertion_point(class_scope:GetDevicesByFilterResponse)
  ))
_sym_db.RegisterMessage(GetDevicesByFilterResponse)

DeviceRequest = _reflection.GeneratedProtocolMessageType('DeviceRequest', (_message.Message,), dict(
  DESCRIPTOR = _DEVICEREQUEST,
  __module__ = 'device_state_requests_pb2'
  # @@protoc_insertion_point(class_scope:DeviceRequest)
  ))
_sym_db.RegisterMessage(DeviceRequest)

DeviceResponse = _reflection.GeneratedProtocolMessageType('DeviceResponse', (_message.Message,), dict(
  DESCRIPTOR = _DEVICERESPONSE,
  __module__ = 'device_state_requests_pb2'
  # @@protoc_insertion_point(class_scope:DeviceResponse)
  ))
_sym_db.RegisterMessage(DeviceResponse)

DeviceResponseError = _reflection.GeneratedProtocolMessageType('DeviceResponseError', (_message.Message,), dict(
  DESCRIPTOR = _DEVICERESPONSEERROR,
  __module__ = 'device_state_requests_pb2'
  # @@protoc_insertion_point(class_scope:DeviceResponseError)
  ))
_sym_db.RegisterMessage(DeviceResponseError)


# @@protoc_insertion_point(module_scope)
