# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: firmware_structures.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='firmware_structures.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x19\x66irmware_structures.proto\x1a\x0c\x63ommon.proto\"w\n\x18\x43omponentFirmwareVersion\x12\x17\n\x0fpackage_version\x18\x01 \x01(\t\x12\x15\n\rvideo_version\x18\x02 \x01(\t\x12\x16\n\x0e\x65\x65prom_version\x18\x03 \x01(\t\x12\x13\n\x0b\x62le_version\x18\x04 \x01(\t\"\xb4\x01\n\x15\x44\x65viceFirmwareVersion\x12\x13\n\x0b\x64\x65vice_uuid\x18\x01 \x01(\t\x12*\n\x07version\x18\x02 \x01(\x0b\x32\x19.ComponentFirmwareVersion\x12$\n\x1cis_firmware_update_available\x18\x03 \x01(\x08\x12\x34\n\x11\x61vailable_version\x18\x04 \x01(\x0b\x32\x19.ComponentFirmwareVersion\"u\n\x1c\x44\x65viceFirmwareUpdateProgress\x12\x13\n\x0b\x64\x65vice_uuid\x18\x01 \x01(\t\x12\x10\n\x08progress\x18\x02 \x01(\x02\x12.\n\x0bupdating_to\x18\x03 \x01(\x0b\x32\x19.ComponentFirmwareVersion\";\n\rFirmwareError\x12\x13\n\x0b\x64\x65vice_uuid\x18\x01 \x01(\t\x12\x15\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x06.Errorb\x06proto3')
  ,
  dependencies=[common__pb2.DESCRIPTOR,])




_COMPONENTFIRMWAREVERSION = _descriptor.Descriptor(
  name='ComponentFirmwareVersion',
  full_name='ComponentFirmwareVersion',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='package_version', full_name='ComponentFirmwareVersion.package_version', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='video_version', full_name='ComponentFirmwareVersion.video_version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='eeprom_version', full_name='ComponentFirmwareVersion.eeprom_version', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ble_version', full_name='ComponentFirmwareVersion.ble_version', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=162,
)


_DEVICEFIRMWAREVERSION = _descriptor.Descriptor(
  name='DeviceFirmwareVersion',
  full_name='DeviceFirmwareVersion',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='device_uuid', full_name='DeviceFirmwareVersion.device_uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='DeviceFirmwareVersion.version', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_firmware_update_available', full_name='DeviceFirmwareVersion.is_firmware_update_available', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='available_version', full_name='DeviceFirmwareVersion.available_version', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=165,
  serialized_end=345,
)


_DEVICEFIRMWAREUPDATEPROGRESS = _descriptor.Descriptor(
  name='DeviceFirmwareUpdateProgress',
  full_name='DeviceFirmwareUpdateProgress',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='device_uuid', full_name='DeviceFirmwareUpdateProgress.device_uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='progress', full_name='DeviceFirmwareUpdateProgress.progress', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='updating_to', full_name='DeviceFirmwareUpdateProgress.updating_to', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=347,
  serialized_end=464,
)


_FIRMWAREERROR = _descriptor.Descriptor(
  name='FirmwareError',
  full_name='FirmwareError',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='device_uuid', full_name='FirmwareError.device_uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='FirmwareError.error', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=466,
  serialized_end=525,
)

_DEVICEFIRMWAREVERSION.fields_by_name['version'].message_type = _COMPONENTFIRMWAREVERSION
_DEVICEFIRMWAREVERSION.fields_by_name['available_version'].message_type = _COMPONENTFIRMWAREVERSION
_DEVICEFIRMWAREUPDATEPROGRESS.fields_by_name['updating_to'].message_type = _COMPONENTFIRMWAREVERSION
_FIRMWAREERROR.fields_by_name['error'].message_type = common__pb2._ERROR
DESCRIPTOR.message_types_by_name['ComponentFirmwareVersion'] = _COMPONENTFIRMWAREVERSION
DESCRIPTOR.message_types_by_name['DeviceFirmwareVersion'] = _DEVICEFIRMWAREVERSION
DESCRIPTOR.message_types_by_name['DeviceFirmwareUpdateProgress'] = _DEVICEFIRMWAREUPDATEPROGRESS
DESCRIPTOR.message_types_by_name['FirmwareError'] = _FIRMWAREERROR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ComponentFirmwareVersion = _reflection.GeneratedProtocolMessageType('ComponentFirmwareVersion', (_message.Message,), dict(
  DESCRIPTOR = _COMPONENTFIRMWAREVERSION,
  __module__ = 'firmware_structures_pb2'
  # @@protoc_insertion_point(class_scope:ComponentFirmwareVersion)
  ))
_sym_db.RegisterMessage(ComponentFirmwareVersion)

DeviceFirmwareVersion = _reflection.GeneratedProtocolMessageType('DeviceFirmwareVersion', (_message.Message,), dict(
  DESCRIPTOR = _DEVICEFIRMWAREVERSION,
  __module__ = 'firmware_structures_pb2'
  # @@protoc_insertion_point(class_scope:DeviceFirmwareVersion)
  ))
_sym_db.RegisterMessage(DeviceFirmwareVersion)

DeviceFirmwareUpdateProgress = _reflection.GeneratedProtocolMessageType('DeviceFirmwareUpdateProgress', (_message.Message,), dict(
  DESCRIPTOR = _DEVICEFIRMWAREUPDATEPROGRESS,
  __module__ = 'firmware_structures_pb2'
  # @@protoc_insertion_point(class_scope:DeviceFirmwareUpdateProgress)
  ))
_sym_db.RegisterMessage(DeviceFirmwareUpdateProgress)

FirmwareError = _reflection.GeneratedProtocolMessageType('FirmwareError', (_message.Message,), dict(
  DESCRIPTOR = _FIRMWAREERROR,
  __module__ = 'firmware_structures_pb2'
  # @@protoc_insertion_point(class_scope:FirmwareError)
  ))
_sym_db.RegisterMessage(FirmwareError)


# @@protoc_insertion_point(module_scope)
