# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: firmware_events.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import firmware_structures_pb2 as firmware__structures__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='firmware_events.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x15\x66irmware_events.proto\x1a\x19\x66irmware_structures.proto\"Q\n\x1c\x46irmwareUpdateAvailableEvent\x12\x31\n\x11\x61vailable_updates\x18\x01 \x03(\x0b\x32\x16.DeviceFirmwareVersion\"N\n\x1b\x46irmwareUpdateProgressEvent\x12/\n\x08progress\x18\x01 \x01(\x0b\x32\x1d.DeviceFirmwareUpdateProgress\"\x95\x01\n\x1a\x46irmwareUpdateStartedEvent\x12\x13\n\x0b\x64\x65vice_uuid\x18\x01 \x01(\t\x12\x32\n\x0f\x63urrent_version\x18\x02 \x01(\x0b\x32\x19.ComponentFirmwareVersion\x12.\n\x0bupdating_to\x18\x03 \x01(\x0b\x32\x19.ComponentFirmwareVersion\"b\n\x1c\x46irmwareUpdateCompletedEvent\x12\x13\n\x0b\x64\x65vice_uuid\x18\x01 \x01(\t\x12-\n\nupdated_to\x18\x02 \x01(\x0b\x32\x19.ComponentFirmwareVersion\"9\n\x18\x46irmwareUpdateErrorEvent\x12\x1d\n\x05\x65rror\x18\x01 \x01(\x0b\x32\x0e.FirmwareError\"\xb2\x02\n\rFirmwareEvent\x12H\n\x1f\x66irmware_update_available_event\x18\x01 \x01(\x0b\x32\x1d.FirmwareUpdateAvailableEventH\x00\x12\x46\n\x1e\x66irmware_update_progress_event\x18\x02 \x01(\x0b\x32\x1c.FirmwareUpdateProgressEventH\x00\x12\x44\n\x1d\x66irmware_update_started_event\x18\x03 \x01(\x0b\x32\x1b.FirmwareUpdateStartedEventH\x00\x12@\n\x1b\x66irmware_update_error_event\x18\x04 \x01(\x0b\x32\x19.FirmwareUpdateErrorEventH\x00\x42\x07\n\x05\x65ventb\x06proto3')
  ,
  dependencies=[firmware__structures__pb2.DESCRIPTOR,])




_FIRMWAREUPDATEAVAILABLEEVENT = _descriptor.Descriptor(
  name='FirmwareUpdateAvailableEvent',
  full_name='FirmwareUpdateAvailableEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='available_updates', full_name='FirmwareUpdateAvailableEvent.available_updates', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=133,
)


_FIRMWAREUPDATEPROGRESSEVENT = _descriptor.Descriptor(
  name='FirmwareUpdateProgressEvent',
  full_name='FirmwareUpdateProgressEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='progress', full_name='FirmwareUpdateProgressEvent.progress', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=135,
  serialized_end=213,
)


_FIRMWAREUPDATESTARTEDEVENT = _descriptor.Descriptor(
  name='FirmwareUpdateStartedEvent',
  full_name='FirmwareUpdateStartedEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='device_uuid', full_name='FirmwareUpdateStartedEvent.device_uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='current_version', full_name='FirmwareUpdateStartedEvent.current_version', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='updating_to', full_name='FirmwareUpdateStartedEvent.updating_to', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=216,
  serialized_end=365,
)


_FIRMWAREUPDATECOMPLETEDEVENT = _descriptor.Descriptor(
  name='FirmwareUpdateCompletedEvent',
  full_name='FirmwareUpdateCompletedEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='device_uuid', full_name='FirmwareUpdateCompletedEvent.device_uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='updated_to', full_name='FirmwareUpdateCompletedEvent.updated_to', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=367,
  serialized_end=465,
)


_FIRMWAREUPDATEERROREVENT = _descriptor.Descriptor(
  name='FirmwareUpdateErrorEvent',
  full_name='FirmwareUpdateErrorEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='FirmwareUpdateErrorEvent.error', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=467,
  serialized_end=524,
)


_FIRMWAREEVENT = _descriptor.Descriptor(
  name='FirmwareEvent',
  full_name='FirmwareEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='firmware_update_available_event', full_name='FirmwareEvent.firmware_update_available_event', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='firmware_update_progress_event', full_name='FirmwareEvent.firmware_update_progress_event', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='firmware_update_started_event', full_name='FirmwareEvent.firmware_update_started_event', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='firmware_update_error_event', full_name='FirmwareEvent.firmware_update_error_event', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='event', full_name='FirmwareEvent.event',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=527,
  serialized_end=833,
)

_FIRMWAREUPDATEAVAILABLEEVENT.fields_by_name['available_updates'].message_type = firmware__structures__pb2._DEVICEFIRMWAREVERSION
_FIRMWAREUPDATEPROGRESSEVENT.fields_by_name['progress'].message_type = firmware__structures__pb2._DEVICEFIRMWAREUPDATEPROGRESS
_FIRMWAREUPDATESTARTEDEVENT.fields_by_name['current_version'].message_type = firmware__structures__pb2._COMPONENTFIRMWAREVERSION
_FIRMWAREUPDATESTARTEDEVENT.fields_by_name['updating_to'].message_type = firmware__structures__pb2._COMPONENTFIRMWAREVERSION
_FIRMWAREUPDATECOMPLETEDEVENT.fields_by_name['updated_to'].message_type = firmware__structures__pb2._COMPONENTFIRMWAREVERSION
_FIRMWAREUPDATEERROREVENT.fields_by_name['error'].message_type = firmware__structures__pb2._FIRMWAREERROR
_FIRMWAREEVENT.fields_by_name['firmware_update_available_event'].message_type = _FIRMWAREUPDATEAVAILABLEEVENT
_FIRMWAREEVENT.fields_by_name['firmware_update_progress_event'].message_type = _FIRMWAREUPDATEPROGRESSEVENT
_FIRMWAREEVENT.fields_by_name['firmware_update_started_event'].message_type = _FIRMWAREUPDATESTARTEDEVENT
_FIRMWAREEVENT.fields_by_name['firmware_update_error_event'].message_type = _FIRMWAREUPDATEERROREVENT
_FIRMWAREEVENT.oneofs_by_name['event'].fields.append(
  _FIRMWAREEVENT.fields_by_name['firmware_update_available_event'])
_FIRMWAREEVENT.fields_by_name['firmware_update_available_event'].containing_oneof = _FIRMWAREEVENT.oneofs_by_name['event']
_FIRMWAREEVENT.oneofs_by_name['event'].fields.append(
  _FIRMWAREEVENT.fields_by_name['firmware_update_progress_event'])
_FIRMWAREEVENT.fields_by_name['firmware_update_progress_event'].containing_oneof = _FIRMWAREEVENT.oneofs_by_name['event']
_FIRMWAREEVENT.oneofs_by_name['event'].fields.append(
  _FIRMWAREEVENT.fields_by_name['firmware_update_started_event'])
_FIRMWAREEVENT.fields_by_name['firmware_update_started_event'].containing_oneof = _FIRMWAREEVENT.oneofs_by_name['event']
_FIRMWAREEVENT.oneofs_by_name['event'].fields.append(
  _FIRMWAREEVENT.fields_by_name['firmware_update_error_event'])
_FIRMWAREEVENT.fields_by_name['firmware_update_error_event'].containing_oneof = _FIRMWAREEVENT.oneofs_by_name['event']
DESCRIPTOR.message_types_by_name['FirmwareUpdateAvailableEvent'] = _FIRMWAREUPDATEAVAILABLEEVENT
DESCRIPTOR.message_types_by_name['FirmwareUpdateProgressEvent'] = _FIRMWAREUPDATEPROGRESSEVENT
DESCRIPTOR.message_types_by_name['FirmwareUpdateStartedEvent'] = _FIRMWAREUPDATESTARTEDEVENT
DESCRIPTOR.message_types_by_name['FirmwareUpdateCompletedEvent'] = _FIRMWAREUPDATECOMPLETEDEVENT
DESCRIPTOR.message_types_by_name['FirmwareUpdateErrorEvent'] = _FIRMWAREUPDATEERROREVENT
DESCRIPTOR.message_types_by_name['FirmwareEvent'] = _FIRMWAREEVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FirmwareUpdateAvailableEvent = _reflection.GeneratedProtocolMessageType('FirmwareUpdateAvailableEvent', (_message.Message,), dict(
  DESCRIPTOR = _FIRMWAREUPDATEAVAILABLEEVENT,
  __module__ = 'firmware_events_pb2'
  # @@protoc_insertion_point(class_scope:FirmwareUpdateAvailableEvent)
  ))
_sym_db.RegisterMessage(FirmwareUpdateAvailableEvent)

FirmwareUpdateProgressEvent = _reflection.GeneratedProtocolMessageType('FirmwareUpdateProgressEvent', (_message.Message,), dict(
  DESCRIPTOR = _FIRMWAREUPDATEPROGRESSEVENT,
  __module__ = 'firmware_events_pb2'
  # @@protoc_insertion_point(class_scope:FirmwareUpdateProgressEvent)
  ))
_sym_db.RegisterMessage(FirmwareUpdateProgressEvent)

FirmwareUpdateStartedEvent = _reflection.GeneratedProtocolMessageType('FirmwareUpdateStartedEvent', (_message.Message,), dict(
  DESCRIPTOR = _FIRMWAREUPDATESTARTEDEVENT,
  __module__ = 'firmware_events_pb2'
  # @@protoc_insertion_point(class_scope:FirmwareUpdateStartedEvent)
  ))
_sym_db.RegisterMessage(FirmwareUpdateStartedEvent)

FirmwareUpdateCompletedEvent = _reflection.GeneratedProtocolMessageType('FirmwareUpdateCompletedEvent', (_message.Message,), dict(
  DESCRIPTOR = _FIRMWAREUPDATECOMPLETEDEVENT,
  __module__ = 'firmware_events_pb2'
  # @@protoc_insertion_point(class_scope:FirmwareUpdateCompletedEvent)
  ))
_sym_db.RegisterMessage(FirmwareUpdateCompletedEvent)

FirmwareUpdateErrorEvent = _reflection.GeneratedProtocolMessageType('FirmwareUpdateErrorEvent', (_message.Message,), dict(
  DESCRIPTOR = _FIRMWAREUPDATEERROREVENT,
  __module__ = 'firmware_events_pb2'
  # @@protoc_insertion_point(class_scope:FirmwareUpdateErrorEvent)
  ))
_sym_db.RegisterMessage(FirmwareUpdateErrorEvent)

FirmwareEvent = _reflection.GeneratedProtocolMessageType('FirmwareEvent', (_message.Message,), dict(
  DESCRIPTOR = _FIRMWAREEVENT,
  __module__ = 'firmware_events_pb2'
  # @@protoc_insertion_point(class_scope:FirmwareEvent)
  ))
_sym_db.RegisterMessage(FirmwareEvent)


# @@protoc_insertion_point(module_scope)
